dependencies:
  basic_utils: 5.7.0
  collection: ^1.17.2
  common:
    path: ../common
  dart_mappable: 4.2.2
  desktop_drop: 0.5.0
  device_apps: 2.2.0
  dio: 5.7.0
  dynamic_color: 1.7.0
  flutter:
    sdk: flutter
  flutter_displaymode: 0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: 0.7.3+1
  gal: 2.3.0
  intl: ^0.19.0
  legalize: ^1.2.2
  logging: 1.2.0
  mime: 1.0.6
  nanoid2: 2.0.1
  network_info_plus: 6.0.1
  pasteboard: 0.3.0
  path: 1.9.0
  path_provider_foundation: 2.4.0
  pretty_qr_code: 3.3.0
  refena_flutter: 2.1.1
  refena_inspector_client: 2.0.0
  routerino: 0.8.0
  saf_stream: 0.7.5
  screen_retriever: 0.1.9
  share_handler: 0.0.19
  share_handler_ios: 0.0.12
  shared_preferences_platform_interface: any
  shared_storage: 0.8.1
  slang: 4.1.0
  slang_flutter: 4.1.0
  system_settings: 2.1.0
  tray_manager: 0.2.3
  uri_content: 2.2.0
  uuid: 4.5.0
  wechat_assets_picker: 8.8.1+1
  win32_registry: 1.1.2
  window_manager: 0.3.9
  windows_taskbar: 1.1.2
  yaru: 1.2.2
dependency_overrides:
  connectivity_plus:
    git:
      path: packages/connectivity_plus/connectivity_plus
      url: https://gitee.com/openharmony-sig/flutter_plus_plugins.git
  device_info_plus:
    git:
      path: packages/device_info_plus/device_info_plus
      url: https://gitee.com/openharmony-sig/flutter_plus_plugins.git
  file_picker:
    git:
      url: https://gitee.com/openharmony-sig/fluttertpc_file_picker.git
  file_picker_ohos:
    path: ./fluttertpc_file_picker/ohos
  file_selector:
    git:
      path: packages/file_selector/file_selector
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  fluttertoast:
    git: https://gitee.com/openharmony-sig/flutter_fluttertoast.git
  image_picker:
    git:
      path: packages/image_picker/image_picker
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  in_app_purchase:
    git:
      path: packages/in_app_purchase/in_app_purchase
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  intl: ^0.19.0
  open_filex:
    git:
      url: https://gitee.com/openharmony-sig/fluttertpc_open_filex.git
  package_info_plus:
    git:
      path: packages/package_info_plus/package_info_plus
      url: https://gitee.com/openharmony-sig/flutter_plus_plugins.git
  path: 1.9.0
  path_provider:
    git:
      path: packages/path_provider/path_provider
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  permission_handler:
    git:
      path: permission_handler
      url: https://gitee.com/openharmony-sig/flutter_permission_handler.git
  permission_handler_windows:
    git:
      ref: 2dadd8afbf81e0e3e4791d7144e689555e58f649
      url: https://github.com/localsend/permission_handler_windows_noop.git
  photo_manager: 2.8.2
  share_plus:
    git:
      path: packages/share_plus/share_plus
      url: https://gitee.com/openharmony-sig/flutter_plus_plugins.git
  shared_preferences:
    git:
      path: packages/shared_preferences/shared_preferences
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  url_launcher:
    git:
      path: packages/url_launcher/url_launcher
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  wakelock_plus:
    git:
      path: wakelock_plus
      url: https://gitee.com/openharmony-sig/fluttertpc_wakelock_plus.git
  webview_flutter:
    git:
      path: packages/webview_flutter/webview_flutter
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  win32: 5.5.4
description: An open source cross-platform alternative to AirDrop
dev_dependencies:
  build_runner: any
  dart_mappable_builder: 4.2.3
  flutter_gen_runner: 5.7.0
  flutter_lints: 4.0.0
  mockito: 5.4.4
  refena_inspector: 2.0.0
  slang_build_runner: any
  slang_gpt: any
  test: ^1.24.3
environment:
  flutter: '>=3.13.0'
  sdk: '>=3.1.0 <4.0.0'
flutter:
  assets:
  - assets/img/
  - assets/web/
  - assets/CHANGELOG.md
  - assets/privacy_policy.html
  uses-material-design: true
flutter_gen:
  line_length: 150
homepage: https://localsend.org/
msix_config:
  architecture: x64
  display_name: AloeChatAI
  identity_name: 11157TienDoNam.AloeChatAI
  languages: en, ar, bn, cs, da, de, el, es-ES, eu, fa, fr, he, hu, in, it, ja, ko,
    ne, nl, pl, pt-BR, ru, sv, th, tr, uk, vi, zh-CN, zh-HK, zh-TW
  logo_path: assets\img\logo-512.png
  os_min_version: 10.0.19041.0
  publisher_display_name: Tien Do Nam
  startup_task:
    enabled: false
    parameters: autostart
    task_id: localsend
name: localsend_app
publish_to: none
version: 1.15.4+54
